import type { InvoiceData } from '../types/invoice';

export const emptyInvoice: InvoiceData = {
  id: 'inv_' + Date.now(),
  invoiceNumber: 'INV-001',
  issueDate: new Date().toISOString().split('T')[0],
  dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  paymentTerms: 'Net 14',
  currency: 'USD',
  status: 'draft',
  business: {
    name: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    stateZip: '',
    country: '',
    taxId: '',
    website: '',
    logoUrl: '',
  },
  client: {
    name: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    stateZip: '',
    country: '',
    clientTaxId: '',
  },
  items: [
    {
      id: 'item_1',
      description: '',
      details: '',
      quantity: 1,
      unitPrice: 0,
    },
  ],
  taxRate: 0,
  discountType: 'percent',
  discountValue: 0,
  shippingFee: 0,
  notes: 'Thank you for your business! Please remit payment within the specified due date.',
  paymentInstructions: 'Bank: Silicon Valley Bank\nAccount Name: Your Business LLC\nAccount No: 1234-5678-9012\nRouting / SWIFT: SVBUS6S',
  themeColor: '#4F46E5', // Indigo
  templateStyle: 'minimal',
};

export const sampleTemplates: { name: string; description: string; data: InvoiceData }[] = [
  {
    name: 'Clean & Minimal',
    description: 'A light, airy design with simple lines and subtle accents',
    data: {
      id: 'inv_sample_minimal',
      invoiceNumber: 'INV-2026-001',
      issueDate: '2026-08-28',
      dueDate: '2026-09-11',
      paymentTerms: 'Net 14',
      currency: 'USD',
      status: 'pending',
      business: {
        name: 'Northstar Studio',
        email: 'hello@northstar.studio',
        phone: '+1 (555) 234-8100',
        address: '890 Market Street, Suite 210',
        city: 'Los Angeles',
        stateZip: 'CA 90014',
        country: 'United States',
        taxId: 'US-EIN-12-3456789',
        website: 'https://northstar.studio',
        logoUrl: '',
      },
      client: {
        name: 'Brightline Consulting Co.',
        email: 'accounts@brightline.co',
        phone: '+1 (555) 910-2200',
        address: '44 Harbor Drive',
        city: 'San Diego',
        stateZip: 'CA 92101',
        country: 'United States',
        clientTaxId: 'US-88-4455667',
      },
      items: [
        {
          id: 'item_1',
          description: 'Brand Identity Package',
          details: 'Logo suite, color palette, and brand guidelines',
          quantity: 1,
          unitPrice: 2600,
        },
        {
          id: 'item_2',
          description: 'Website Redesign',
          details: 'Marketing site design and responsive build-out',
          quantity: 1,
          unitPrice: 4800,
        },
        {
          id: 'item_3',
          description: 'Monthly Support Retainer',
          details: 'Ongoing maintenance, updates, and small revisions',
          quantity: 3,
          unitPrice: 350,
        },
      ],
      taxRate: 8.5,
      discountType: 'percent',
      discountValue: 5,
      shippingFee: 0,
      notes: 'Thank you for your business! Please reach out with any questions.',
      paymentInstructions: 'Bank: Silicon Valley Bank\nAccount Name: Northstar Studio\nAccount: 4890-2341-9871\nRouting: 021000021\nACH / Wire accepted.',
      themeColor: '#0EA5E9',
      templateStyle: 'minimal',
    },
  },
  {
    name: 'Modern & Bold',
    description: 'A striking layout with strong color blocks and confident type',
    data: {
      id: 'inv_sample_modern',
      invoiceNumber: 'INV-MOD-2026-084',
      issueDate: '2026-08-28',
      dueDate: '2026-09-11',
      paymentTerms: 'Net 14',
      currency: 'USD',
      status: 'pending',
      business: {
        name: 'Apex Studio Design & Code',
        email: 'alex@apexstudio.io',
        phone: '+1 (555) 234-8900',
        address: '742 Innovation Way, Suite 400',
        city: 'San Francisco',
        stateZip: 'CA 94107',
        country: 'United States',
        taxId: 'US-EIN-98-7654321',
        website: 'https://apexstudio.io',
        logoUrl: '',
      },
      client: {
        name: 'HyperScale Technologies Inc.',
        email: 'billing@hyperscale.tech',
        phone: '+1 (555) 890-1234',
        address: '100 Market Street, 12th Floor',
        city: 'San Francisco',
        stateZip: 'CA 94105',
        country: 'United States',
        clientTaxId: 'US-94-1122334',
      },
      items: [
        {
          id: 'item_1',
          description: 'SaaS Platform UI/UX Redesign',
          details: 'Design system, interactive prototypes, and responsive dashboards',
          quantity: 1,
          unitPrice: 3200,
        },
        {
          id: 'item_2',
          description: 'Frontend React Engineering',
          details: 'Component library implementation and API integrations',
          quantity: 40,
          unitPrice: 85,
        },
        {
          id: 'item_3',
          description: 'Performance Audit',
          details: 'Core Web Vitals tuning and optimization',
          quantity: 1,
          unitPrice: 650,
        },
      ],
      taxRate: 8.5,
      discountType: 'percent',
      discountValue: 5,
      shippingFee: 0,
      notes: 'Thank you for partnering with Apex Studio! We look forward to the next milestone.',
      paymentInstructions: 'Bank: JPMorgan Chase\nAccount Name: Apex Studio LLC\nAccount: 4890-2341-9871\nRouting: 021000021\nACH / Wire Transfer accepted.',
      themeColor: '#7C3AED',
      templateStyle: 'modern',
    },
  },
  {
    name: 'Classic & Professional',
    description: 'An elegant, traditional design with formal serif typography',
    data: {
      id: 'inv_sample_classic',
      invoiceNumber: 'INV-CLASSIC-4502',
      issueDate: '2026-08-20',
      dueDate: '2026-09-19',
      paymentTerms: 'Net 30',
      currency: 'USD',
      status: 'pending',
      business: {
        name: 'Meridian Partners LLP',
        email: 'invoicing@meridianpartners.com',
        phone: '+1 (212) 555-0148',
        address: '25 Broad Street, 8th Floor',
        city: 'New York',
        stateZip: 'NY 10004',
        country: 'United States',
        taxId: 'US-EIN-11-9876543',
        website: 'https://meridianpartners.com',
        logoUrl: '',
      },
      client: {
        name: 'Ashford & Bennett Co.',
        email: 'accounts@ashfordbennett.com',
        phone: '+1 (646) 555-0199',
        address: '1 Madison Avenue',
        city: 'New York',
        stateZip: 'NY 10010',
        country: 'United States',
        clientTaxId: 'US-33-2211009',
      },
      items: [
        {
          id: 'item_1',
          description: 'Strategic Advisory & Consulting',
          details: 'Quarterly planning and executive guidance',
          quantity: 12,
          unitPrice: 240,
        },
        {
          id: 'item_2',
          description: 'Operational Audit & Reporting',
          details: 'Comprehensive review and detailed report',
          quantity: 1,
          unitPrice: 3300,
        },
        {
          id: 'item_3',
          description: 'Risk Assessment Workshop',
          details: '2-day facilitated session with working sessions',
          quantity: 2,
          unitPrice: 950,
        },
      ],
      taxRate: 8.5,
      discountType: 'percent',
      discountValue: 0,
      shippingFee: 0,
      notes: 'Payment is due within 30 days of the invoice date. Please remit payment promptly.',
      paymentInstructions: 'Bank: Bank of America\nAccount Name: Meridian Partners LLP\nAccount: 88776655\nRouting: 026009593\nWire / ACH accepted.',
      themeColor: '#1E3A5F',
      templateStyle: 'classic',
    },
  },
];
