import type { InvoiceData } from '../types/invoice';

export const emptyInvoice: InvoiceData = {
  id: 'inv_' + Date.now(),
  invoiceNumber: 'INV-001',
  issueDate: new Date().toISOString().split('T')[0],
  dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  paymentTerms: 'Net 14',
  currency: 'USD',
  status: 'draft',
  business: {
    name: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    stateZip: '',
    country: '',
    taxId: '',
    website: '',
    logoUrl: '',
  },
  client: {
    name: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    stateZip: '',
    country: '',
    clientTaxId: '',
  },
  items: [
    {
      id: 'item_1',
      description: '',
      details: '',
      quantity: 1,
      unitPrice: 0,
    },
  ],
  taxRate: 0,
  discountType: 'percent',
  discountValue: 0,
  shippingFee: 0,
  notes: 'Thank you for your business! Please remit payment within the specified due date.',
  paymentInstructions: 'Bank: Silicon Valley Bank\nAccount Name: Your Business LLC\nAccount No: 1234-5678-9012\nRouting / SWIFT: SVBUS6S',
  themeColor: '#4F46E5', // Indigo
  templateStyle: 'modern',
};

export const sampleTemplates: { name: string; description: string; data: InvoiceData }[] = [
  {
    name: 'Web & UI/UX Freelancer',
    description: 'Full-stack development, brand identity, and UI design project',
    data: {
      id: 'inv_sample_web',
      invoiceNumber: 'INV-2026-084',
      issueDate: '2026-08-28',
      dueDate: '2026-09-11',
      paymentTerms: 'Net 14',
      currency: 'USD',
      status: 'pending',
      business: {
        name: 'Apex Studio Design & Code',
        email: 'alex@apexstudio.io',
        phone: '+1 (555) 234-8900',
        address: '742 Innovation Way, Suite 400',
        city: 'San Francisco',
        stateZip: 'CA 94107',
        country: 'United States',
        taxId: 'US-EIN-98-7654321',
        website: 'https://apexstudio.io',
        logoUrl: '',
      },
      client: {
        name: 'HyperScale Technologies Inc.',
        email: 'billing@hyperscale.tech',
        phone: '+1 (555) 890-1234',
        address: '100 Market Street, 12th Floor',
        city: 'San Francisco',
        stateZip: 'CA 94105',
        country: 'United States',
        clientTaxId: 'US-94-1122334',
      },
      items: [
        {
          id: 'item_1',
          description: 'SaaS Platform UI/UX Redesign',
          details: 'Design system, interactive Figma prototypes, and responsive dashboards',
          quantity: 1,
          unitPrice: 3200,
        },
        {
          id: 'item_2',
          description: 'Frontend React + TypeScript Engineering',
          details: 'Component library implementation, API integrations & performance optimization',
          quantity: 40,
          unitPrice: 85,
        },
        {
          id: 'item_3',
          description: 'SEO & Performance Audit',
          details: 'Core Web Vitals tuning, Lighthouse 95+ score achievement, meta schemas',
          quantity: 1,
          unitPrice: 650,
        },
      ],
      taxRate: 8.5,
      discountType: 'percent',
      discountValue: 5,
      shippingFee: 0,
      notes: 'Thank you for partnering with Apex Studio! We look forward to Phase 2 rollout next month.',
      paymentInstructions: 'Bank: JPMorgan Chase\nAccount Name: Apex Studio LLC\nAccount: 4890-2341-9871\nRouting: 021000021\nACH / Wire Transfer accepted.',
      themeColor: '#4F46E5',
      templateStyle: 'modern',
    },
  },
  {
    name: 'Creative Agency / Photography',
    description: 'Commercial photoshoot, video editing & brand assets',
    data: {
      id: 'inv_sample_creative',
      invoiceNumber: 'INV-CREATIVE-109',
      issueDate: '2026-08-25',
      dueDate: '2026-09-08',
      paymentTerms: 'Net 14',
      currency: 'EUR',
      status: 'paid',
      business: {
        name: 'Lumière Visuals Studio',
        email: 'contact@lumierevisuals.eu',
        phone: '+33 1 42 68 55 00',
        address: '18 Rue de la Paix',
        city: 'Paris',
        stateZip: '75002',
        country: 'France',
        taxId: 'FR 32 123456789',
        website: 'https://lumierevisuals.eu',
        logoUrl: '',
      },
      client: {
        name: 'Maison Belle Paris',
        email: 'compta@maisonbelle.fr',
        phone: '+33 1 55 20 40 10',
        address: '45 Avenue Montaigne',
        city: 'Paris',
        stateZip: '75008',
        country: 'France',
        clientTaxId: 'FR 88 987654321',
      },
      items: [
        {
          id: 'item_1',
          description: 'Autumn Collection 2-Day Commercial Shoot',
          details: 'On-location studio, lighting setup, 2 high-res camera rigs',
          quantity: 2,
          unitPrice: 1400,
        },
        {
          id: 'item_2',
          description: 'High-End Retouching & Color Grading',
          details: '35 Master hero shots with print-ready CMYK and digital RGB delivery',
          quantity: 35,
          unitPrice: 40,
        },
        {
          id: 'item_3',
          description: 'Commercial Digital Licensing (1 Year Worldwide)',
          details: 'Full web, social media and billboard advertising usage rights',
          quantity: 1,
          unitPrice: 950,
        },
      ],
      taxRate: 20,
      discountType: 'fixed',
      discountValue: 150,
      shippingFee: 0,
      notes: 'High-resolution RAW assets delivered via secure client gallery. Thank you for your collaboration!',
      paymentInstructions: 'Bank: BNP Paribas\nIBAN: FR76 3000 4000 5000 6000 7000 890\nBIC: BNPAFR22XXX\nReference: INV-CREATIVE-109',
      themeColor: '#059669',
      templateStyle: 'minimal',
    },
  },
  {
    name: 'Management & Strategy Consulting',
    description: 'Executive advisory, operational audit and strategic roadmap',
    data: {
      id: 'inv_sample_consulting',
      invoiceNumber: 'INV-CON-4502',
      issueDate: '2026-08-20',
      dueDate: '2026-09-19',
      paymentTerms: 'Net 30',
      currency: 'GBP',
      status: 'pending',
      business: {
        name: 'Vanguard Strategy Partners LLP',
        email: 'invoicing@vanguardpartners.co.uk',
        phone: '+44 20 7946 0912',
        address: '25 Bank Street, Canary Wharf',
        city: 'London',
        stateZip: 'E14 5JP',
        country: 'United Kingdom',
        taxId: 'GB 999 8888 77',
        website: 'https://vanguardpartners.co.uk',
        logoUrl: '',
      },
      client: {
        name: 'Nordic Growth Capital AB',
        email: 'accounts@nordicgrowth.se',
        phone: '+46 8 123 4567',
        address: 'Stureplan 4',
        city: 'Stockholm',
        stateZip: '114 35',
        country: 'Sweden',
        clientTaxId: 'SE 556677889901',
      },
      items: [
        {
          id: 'item_1',
          description: 'Q3 Enterprise Architecture & Cloud Migration Advisory',
          details: 'Technical readiness assessment and target-state architecture report',
          quantity: 24,
          unitPrice: 220,
        },
        {
          id: 'item_2',
          description: 'Executive Leadership Workshop & Strategy Session',
          details: '2-day intensive stakeholder alignment session in Stockholm',
          quantity: 2,
          unitPrice: 1800,
        },
        {
          id: 'item_3',
          description: 'Vendor Due Diligence & RFP Analysis',
          details: 'Evaluation of tier-1 software vendors with risk matrix report',
          quantity: 1,
          unitPrice: 2400,
        },
      ],
      taxRate: 20,
      discountType: 'percent',
      discountValue: 0,
      shippingFee: 0,
      notes: 'Payment is due within 30 days of invoice date. All deliverables transferred under standard master service agreement.',
      paymentInstructions: 'Bank: Barclays Bank UK\nAccount Name: Vanguard Strategy Partners\nSort Code: 20-00-00\nAccount: 88776655\nIBAN: GB29 BUKB 2000 0088 7766 55',
      themeColor: '#0F172A',
      templateStyle: 'executive',
    },
  },
];
